import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";
import styles from "../styles/Home.module.scss";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Scrollbar, A11y } from "swiper";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import settings from "../ayarlar.json";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.swiper}>
        <Swiper
          modules={[Pagination]}
          pagination
          slidesPerView={1}
          autoplay={true}
          loop={true}
          height={800}
          centeredSlides={true}
        >
          {settings.carouselItems.map((item) => (
            <SwiperSlide>
              <img key={item.id} src={item.path} />
            </SwiperSlide>
          ))}
        </Swiper>
      </div>
      asd
    </div>
  );
}
